---
- name: Install Clickhouse
  hosts: clickhouse
  tasks:
  - name: install clickhouse
    include_role:
     name: clickhouse
    tags: clickhouse
- name: Install Vector
  hosts: vector
  tasks:
  - include_role:
     name: vector
    tags: vector
- name: Install LightHouse
  hosts: lighthouse
  tasks:
  - include_role:
     name: lighthouse
    tags: lighthouse