---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      #become: true
      ansible.builtin.systemd:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Install clickhouse packages
          ansible.builtin.yum:
           name:
             - "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
           state: present
          with_items: "{{ clickhouse_packages }}"
          notify: Start clickhouse service
      rescue:
       - name: Install clickhouse packages
         ansible.builtin.yum:
            name:
                - "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            state: present
    - name: Flush handlers
      meta: flush_handlers
      notify: Start clickhouse service
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
  tags: clickhouse
- name: Install Vector
  hosts: vector
  vars_files:
    - ./group_vars/vector/vars.yml
  handlers:
    - name: Start vector service
      become: true
      ansible.builtin.systemd:
        name: vector
        state: restarted
        daemon_reload: true
  tasks:
    - name: Install vector
      ansible.builtin.yum:
          name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm"
          state: present
      notify: Start vector service
    - name: copy vector config
      ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_folder }}/vector.yaml"
        mode: 0644
    - name: copy vector service config
      ansible.builtin.template:
        src: vector_service.j2
        dest: /usr/lib/systemd/system/vector.service
        mode: 0644
      notify: Start vector service
  tags: vector          