---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:ivannikita/vector-role.git
    scm: git
    name: vectore 
  - src: git@github.com:ivannikita/lighthouse-role.git
    scm: git
    name: lighthouse 

